import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gtmOsSidebar: [
    { type: 'doc', id: 'intro', label: 'GTM OS - Explained' },
    {
      type: 'category',
      label: '1. Build ($0-1M)',
      link: { type: 'doc', id: 'build/overview' },
      items: [
        'build/overview',
        'build/team-structure',
        'build/sales-processes',
        'build/marketing-processes',
        'build/cs-processes',
        'build/partnerships',
        'build/tech-stack',
        'build/metrics',
        'build/ai-agents',
        'build/risks',
        'build/graduation',
        'build/playbook-mapping',
      ],
    },
    {
      type: 'category',
      label: '2. Stabilize ($1-5M)',
      link: { type: 'doc', id: 'stabilize/overview' },
      items: [
        'stabilize/overview',
        'stabilize/team-structure',
        'stabilize/sales-processes',
        'stabilize/marketing-processes',
        'stabilize/cs-processes',
        'stabilize/partnerships',
        'stabilize/tech-stack',
        'stabilize/metrics',
        'stabilize/ai-agents',
        'stabilize/risks',
        'stabilize/graduation',
        'stabilize/playbook-mapping',
      ],
    },
    {
      type: 'category',
      label: '3. Scale ($5-15M)',
      link: { type: 'doc', id: 'scale/overview' },
      items: [
        'scale/overview',
        'scale/team-structure',
        'scale/sales-processes',
        'scale/marketing-processes',
        'scale/cs-processes',
        'scale/partnerships',
        'scale/tech-stack',
        'scale/metrics',
        'scale/ai-agents',
        'scale/risks',
        'scale/graduation',
        'scale/playbook-mapping',
      ],
    },
    {
      type: 'category',
      label: '4. Optimize ($15-40M)',
      link: { type: 'doc', id: 'optimize/overview' },
      items: [
        'optimize/overview',
        'optimize/team-structure',
        'optimize/sales-processes',
        'optimize/marketing-processes',
        'optimize/cs-processes',
        'optimize/partnerships',
        'optimize/tech-stack',
        'optimize/metrics',
        'optimize/ai-agents',
        'optimize/risks',
        'optimize/graduation',
        'optimize/playbook-mapping',
      ],
    },
    {
      type: 'category',
      label: '5. Platform ($40M+)',
      link: { type: 'doc', id: 'platform/overview' },
      items: [
        'platform/overview',
        'platform/team-structure',
        'platform/sales-processes',
        'platform/marketing-processes',
        'platform/cs-processes',
        'platform/partnerships',
        'platform/tech-stack',
        'platform/metrics',
        'platform/ai-agents',
        'platform/risks',
        'platform/graduation',
        'platform/playbook-mapping',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
        'reference/appendix',
      ],
    },
  ],
};

export default sidebars;
