import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main playbooks sidebar - projects + in-depth section
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
    // Visual divider
    {type: 'html', value: '<hr style="margin: 1rem 0; border-color: #444;" />'},
    // In-Depth section header
    {type: 'html', value: '<span class="sidebar-section-header">In-Depth Playbooks</span>'},
    // In-Depth Playbooks
    {
      type: 'category',
      label: 'Market Map',
      collapsed: true,
      items: [
        {type: 'doc', id: 'in-depth/market-map/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/market-map/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/market-map/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/market-map/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Attribution',
      collapsed: true,
      items: [
        {type: 'doc', id: 'in-depth/attribution/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/attribution/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/attribution/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/attribution/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Automated Inbound',
      collapsed: true,
      items: [
        {type: 'doc', id: 'in-depth/automated-inbound/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/automated-inbound/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/automated-inbound/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/automated-inbound/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Growth Model',
      collapsed: true,
      items: [
        {type: 'doc', id: 'in-depth/growth-model/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/growth-model/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/growth-model/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/growth-model/support', label: '4. Post Support'},
      ],
    },
  ],

  // Separate sidebar for in-depth playbooks (used via front matter)
  inDepthSidebar: [
    {type: 'html', value: '<span class="sidebar-section-header">In-Depth Playbooks</span>'},
    {
      type: 'category',
      label: 'Market Map',
      collapsed: false,
      link: {type: 'doc', id: 'in-depth/market-map/index'},
      items: [
        {type: 'doc', id: 'in-depth/market-map/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/market-map/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/market-map/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/market-map/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Attribution',
      collapsed: false,
      link: {type: 'doc', id: 'in-depth/attribution/index'},
      items: [
        {type: 'doc', id: 'in-depth/attribution/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/attribution/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/attribution/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/attribution/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Automated Inbound',
      collapsed: false,
      link: {type: 'doc', id: 'in-depth/automated-inbound/index'},
      items: [
        {type: 'doc', id: 'in-depth/automated-inbound/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/automated-inbound/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/automated-inbound/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/automated-inbound/support', label: '4. Post Support'},
      ],
    },
    {
      type: 'category',
      label: 'Growth Model',
      collapsed: false,
      link: {type: 'doc', id: 'in-depth/growth-model/index'},
      items: [
        {type: 'doc', id: 'in-depth/growth-model/overview', label: '1. Overview'},
        {type: 'doc', id: 'in-depth/growth-model/methodology', label: '2. Methodology'},
        {type: 'doc', id: 'in-depth/growth-model/implementation', label: '3. Implementation'},
        {type: 'doc', id: 'in-depth/growth-model/support', label: '4. Post Support'},
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
